### PR TITLE
Cherry pick sem20190501 on upstream master

### PR DESCRIPTION
**Pull request by hjmjohnson**
The original tclap code embedded in SlicerExecutionModel is from the upstream tclap hash e5a757999f20eb1964d96c2ef32abf875fa230f4.  Before embedding, all tabs were removed, and cmake build infrastructure was added.  Those <poor> choices resulted in an extremely difficult path for keeping the code base consistent with the upstream version of TCLAP.

First extract tclap subdirectory from SEM to isoloate the changes made.

//https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository
git filter-branch --prune-empty --subdirectory-filter tclap minimize-changes-to-hash-e5a757999f20eb1964d96c2ef32abf875fa230f4

Then cherry-pick each change onto the upstream version based at e5a757999f20eb1964d96c2ef32abf875fa230f4
//https://stackoverflow.com/questions/24412980/how-to-run-git-rebase-and-ignore-whitespace

git cherry-pick -Xignore-all-space b1545f2208a1ccc2ed85a9c6c45716e77742a321
git cherry-pick -Xignore-all-space 55fdec250a60075c96254c3eef8844adadc302d2

Finally, rebase on upstream/master.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@jcfr Do you have any comments not this?  Can it be merged?

**Comment by jcfr** [comment]
Well done.

I suggest we squash all commit together and provide a summary statement.

All contributor can be added using:

```
Co-authored-by: ...  
Co-authored-by: ...  
```

[Here](https://github.com/KitwareMedical/SlicerCustomAppTemplate/commit/8636b2ecbec03f5d7c5c65f026e0cd7b49d558e2) is an example of commit where this was done.

Ultimately the Slicer/tclap project will have two branches:
* `slicer-2006-02-21-e5a757999`: This will hold the version currently used in Slicer
* `slicer-2018-08-02-v1.2-c51fb519d`: This will be the updated version.

**Comment by hjmjohnson** [comment]
Replaced by #2 as requested by @jcfr

**Comment by hjmjohnson** [comment]
@jcfr  slicer-2006-02-21-e5a757999 is not a very reliable source.  The version in SlicerExecutionModel that we start with was modified before being committted (all tabs removed).

It is really hard to know now to syncronize  for that patch. I don't know what you would want in this tree.

**Pull request closed without merging**
